package com.swimpay.receiver.ui.premium

data class PremiumLocalizedCopy(
    val welcomeTitle: String,
    val welcomeBody: String,
    val createAccount: String,
    val signIn: String,
    val chooseProfileTitle: String,
    val sameRights: String,
    val personalProfile: String,
    val personalProfileBody: String,
    val commerceProfile: String,
    val commerceProfileBody: String,
    val recoverTitle: String,
    val recoverBody: String,
    val googleRecovery: String,
    val googleRecoveryBody: String,
    val terminalTitle: String,
    val paymentsGroup: String,
    val banks: String,
    val receivingMethods: String,
    val confirmationMode: String,
    val businessGroup: String,
    val developerIntegration: String,
    val sales: String,
    val notifications: String,
    val applicationGroup: String,
    val appearance: String,
    val language: String,
    val security: String,
    val helpGroup: String,
    val support: String,
    val helpCenter: String,
    val signOut: String,
    val languageBody: String,
    val appearanceBody: String,
    val theme: String,
    val choose: String,
    val active: String
) {
    fun profileLabel(profileType: PremiumMerchantProfileType): String {
        return when (profileType) {
            PremiumMerchantProfileType.PERSONAL -> personalProfile
            PremiumMerchantProfileType.COMMERCE -> commerceProfile
        }
    }

    fun profileBody(profileType: PremiumMerchantProfileType): String {
        return when (profileType) {
            PremiumMerchantProfileType.PERSONAL -> personalProfileBody
            PremiumMerchantProfileType.COMMERCE -> commerceProfileBody
        }
    }

    fun themeModeLabel(mode: PremiumThemeMode): String {
        return when (this) {
            fr -> mode.labelFr
            en -> mode.labelEn
            ru -> mode.labelRu
            else -> mode.labelFr
        }
    }

    fun mainTabLabel(tab: PremiumMainTab): String {
        return when (this) {
            fr -> when (tab) {
                PremiumMainTab.Home -> "Accueil"
                PremiumMainTab.Reviews -> "Revue"
                PremiumMainTab.Payment -> "Paiement"
                PremiumMainTab.Business -> "Business"
                PremiumMainTab.Settings -> "Réglages"
            }
            en -> when (tab) {
                PremiumMainTab.Home -> "Home"
                PremiumMainTab.Reviews -> "Review"
                PremiumMainTab.Payment -> "Payment"
                PremiumMainTab.Business -> "Business"
                PremiumMainTab.Settings -> "Settings"
            }
            ru -> when (tab) {
                PremiumMainTab.Home -> "Главная"
                PremiumMainTab.Reviews -> "Проверка"
                PremiumMainTab.Payment -> "Платежи"
                PremiumMainTab.Business -> "Бизнес"
                PremiumMainTab.Settings -> "Настройки"
            }
            else -> tab.navLabel
        }
    }

    fun ui(text: String): String {
        return translations[text]?.let { localized ->
            when (this) {
                fr -> localized.fr
                en -> localized.en
                ru -> localized.ru
                else -> localized.fr
            }
        } ?: text
    }

    companion object {
        fun forLanguage(language: PremiumLanguageOption): PremiumLocalizedCopy {
            return when (language) {
                PremiumLanguageOption.FR -> fr
                PremiumLanguageOption.EN -> en
                PremiumLanguageOption.RU -> ru
            }
        }

        private data class LocalizedText(val fr: String, val en: String, val ru: String)

        private val translations = listOf(
            LocalizedText("Accueil", "Home", "Главная"),
            LocalizedText("Revue", "Review", "Проверка"),
            LocalizedText("Paiement", "Payment", "Платежи"),
            LocalizedText("Business", "Business", "Бизнес"),
            LocalizedText("Réglages", "Settings", "Настройки"),
            LocalizedText("Compte", "Account", "Аккаунт"),
            LocalizedText("Paiements", "Payments", "Платежи"),
            LocalizedText("Banques", "Banks", "Банки"),
            LocalizedText("Sites", "Sites", "Сайты"),
            LocalizedText("Aide", "Help", "Помощь"),
            LocalizedText("Bonjour, Merchant", "Hello, Merchant", "Здравствуйте, Merchant"),
            LocalizedText("Welcome back", "Welcome back", "С возвращением"),
            LocalizedText("Aujourd'hui", "Today", "Сегодня"),
            LocalizedText("Live", "Live", "Онлайн"),
            LocalizedText("En attente", "Pending", "Ожидание"),
            LocalizedText("Paiements reçus", "Received payments", "Полученные платежи"),
            LocalizedText("Actions rapides", "Quick actions", "Быстрые действия"),
            LocalizedText("Activité", "Activity", "Активность"),
            LocalizedText("Reçu ce mois", "Received this month", "Получено за месяц"),
            LocalizedText("paiements", "payments", "платежей"),
            LocalizedText("vérifiés", "verified", "проверено"),
            LocalizedText("Tous", "All", "Все"),
            LocalizedText("Vérifiés", "Verified", "Проверенные"),
            LocalizedText("En revue", "In review", "На проверке"),
            LocalizedText("À TRAITER", "TO PROCESS", "К ОБРАБОТКЕ"),
            LocalizedText("paiements en revue", "payments in review", "платежей на проверке"),
            LocalizedText("Hier", "Yesterday", "Вчера"),
            LocalizedText("vérifié", "verified", "проверено"),
            LocalizedText("en revue", "in review", "на проверке"),
            LocalizedText("✓ vérifié", "✓ verified", "✓ проверено"),
            LocalizedText("⏳ en revue", "⏳ in review", "⏳ на проверке"),
            LocalizedText("ÉVOLUTION DES PAIEMENTS", "PAYMENT EVOLUTION", "ДИНАМИКА ПЛАТЕЖЕЙ"),
            LocalizedText("Montant", "Amount", "Сумма"),
            LocalizedText("Taux", "Rate", "Доля"),
            LocalizedText("HISTORIQUE DES PAIEMENTS", "PAYMENT HISTORY", "ИСТОРИЯ ПЛАТЕЖЕЙ"),
            LocalizedText("Voir tout", "See all", "Смотреть все"),
            LocalizedText("Les paiements reconnus par SwimPay apparaîtront ici.", "Payments recognized by SwimPay will appear here.", "Платежи, распознанные SwimPay, появятся здесь."),
            LocalizedText("À confirmer", "To confirm", "На проверку"),
            LocalizedText("Confirmés", "Confirmed", "Подтверждены"),
            LocalizedText("Rejetés", "Rejected", "Отклонены"),
            LocalizedText("Expirés", "Expired", "Истекли"),
            LocalizedText("Échecs", "Failed", "Ошибки"),
            LocalizedText("ÉCHECS", "FAILED", "ОШИБКИ"),
            LocalizedText("Paiements confirmés", "Confirmed payments", "Подтвержденные платежи"),
            LocalizedText("Aucun paiement détecté pour le moment", "No payment detected yet", "Платежей пока нет"),
            LocalizedText("Paiements à confirmer", "Payments to confirm", "Платежи на проверку"),
            LocalizedText("Aucun paiement à confirmer", "No payment to confirm", "Нет платежей на проверку"),
            LocalizedText("Les nouveaux paiements apparaîtront ici.", "New payments will appear here.", "Новые платежи появятся здесь."),
            LocalizedText("Confirmez uniquement les paiements que vous reconnaissez.", "Only confirm payments you recognize.", "Подтверждайте только знакомые платежи."),
            LocalizedText("Tout", "All", "Все"),
            LocalizedText("Paiement à confirmer", "Payment to confirm", "Платеж на проверку"),
            LocalizedText("Réf.", "Ref.", "Реф."),
            LocalizedText("ORIGINE", "SOURCE", "ИСТОЧНИК"),
            LocalizedText("Détection automatique", "Automatic detection", "Автоматическое обнаружение"),
            LocalizedText("Examiner", "Review", "Проверить"),
            LocalizedText("Vérifier ce paiement", "Review this payment", "Проверить платеж"),
            LocalizedText("POURQUOI VÉRIFIER ?", "WHY REVIEW?", "ПОЧЕМУ НУЖНА ПРОВЕРКА?"),
            LocalizedText("PARCOURS DU PAIEMENT", "PAYMENT TIMELINE", "ХОД ПЛАТЕЖА"),
            LocalizedText("Confirmer reçu", "Confirm received", "Подтвердить получение"),
            LocalizedText("Rejeter le signal", "Reject signal", "Отклонить сигнал"),
            LocalizedText("Annuler la commande", "Cancel order", "Отменить заказ"),
            LocalizedText("Moyens de réception", "Receiving methods", "Способы получения"),
            LocalizedText("Ajoutez les cartes ou numéros que vos clients utiliseront pour vous payer.", "Add the cards or phone numbers your customers will use to pay you.", "Добавьте карты или номера, по которым клиенты будут платить."),
            LocalizedText("Les informations complètes ne sont jamais envoyées dans les webhooks.", "Full details are never sent in webhooks.", "Полные данные никогда не отправляются в вебхуки."),
            LocalizedText("Ajouter une carte", "Add a card", "Добавить карту"),
            LocalizedText("Ajouter téléphone SBP", "Add SBP phone", "Добавить телефон СБП"),
            LocalizedText("Choisissez comment vous recevez l'argent de vos clients.", "Choose how you receive money from your customers.", "Выберите, как вы получаете деньги от клиентов."),
            LocalizedText("Banques russes", "Russian banks", "Российские банки"),
            LocalizedText("Carte · SBP · RUB", "Card · SBP · RUB", "Карта · СБП · RUB"),
            LocalizedText("Carte bancaire et SBP, encaissement en roubles (RUB).", "Bank card and SBP, collection in rubles (RUB).", "Банковская карта и СБП, приём в рублях (RUB)."),
            LocalizedText("Orange, Wave, MTN et plus — encaissement en franc CFA (XOF).", "Orange, Wave, MTN and more — collection in CFA franc (XOF).", "Orange, Wave, MTN и другие — приём во франках КФА (XOF)."),
            LocalizedText("Gérer mes banques", "Manage my banks", "Управлять банками"),
            LocalizedText("Gérer mes wallets", "Manage my wallets", "Управлять кошельками"),
            LocalizedText("Configurer", "Set up", "Настроить"),
            LocalizedText("Choisissez votre wallet", "Choose your wallet", "Выберите кошелёк"),
            LocalizedText("Mobile money (Afrique de l'Ouest)", "Mobile money (West Africa)", "Mobile money (Западная Африка)"),
            LocalizedText("Orange · Wave · MTN · XOF", "Orange · Wave · MTN · XOF", "Orange · Wave · MTN · XOF"),
            LocalizedText("Les paiements ouest-africains sont confirmés manuellement (modèle SwimPay).", "West Africa payments are confirmed manually (SwimPay model).", "Платежи Западной Африки подтверждаются вручную (модель SwimPay)."),
            LocalizedText("À configurer", "To set up", "Настроить"),
            LocalizedText("Mobile money", "Mobile money", "Mobile money"),
            LocalizedText("Ajoutez le wallet sur lequel vos clients vous paient en franc CFA (XOF).", "Add the wallet your customers pay you on in CFA franc (XOF).", "Добавьте кошелёк, на который клиенты платят вам во франках КФА (XOF)."),
            LocalizedText("Ajouter un wallet", "Add a wallet", "Добавить кошелёк"),
            LocalizedText("Choisissez votre wallet, puis saisissez le numéro qui reçoit l'argent.", "Choose your wallet, then enter the number that receives the money.", "Выберите кошелёк, затем введите номер для получения денег."),
            LocalizedText("Numéro mobile money", "Mobile money number", "Номер mobile money"),
            LocalizedText("Format international. Seule la version masquée sera affichée.", "International format. Only the masked version is shown.", "Международный формат. Показывается только скрытая версия."),
            LocalizedText("Enregistrer le wallet", "Save wallet", "Сохранить кошелёк"),
            LocalizedText("Aucun wallet mobile money", "No mobile money wallet", "Нет кошелька mobile money"),
            LocalizedText("Ajoutez un wallet Orange Money, Wave ou MTN pour encaisser en XOF.", "Add an Orange Money, Wave or MTN wallet to collect in XOF.", "Добавьте кошелёк Orange Money, Wave или MTN для приёма в XOF."),
            LocalizedText("Carte bancaire associée à votre banque", "Bank card linked to your bank", "Банковская карта, связанная с банком"),
            LocalizedText("Numéro de téléphone associé à une banque", "Phone number linked to a bank", "Телефон, связанный с банком"),
            LocalizedText("Carte marchand", "Merchant card", "Карта продавца"),
            LocalizedText("Carte à ajouter", "Card to add", "Карта для добавления"),
            LocalizedText("Aucune carte enregistrée", "No saved card", "Сохраненных карт нет"),
            LocalizedText("Non configuré", "Not configured", "Не настроено"),
            LocalizedText("Téléphone à ajouter", "Phone to add", "Телефон для добавления"),
            LocalizedText("Ajoutez un numéro SBP pour l’afficher ici.", "Add an SBP phone number to show it here.", "Добавьте телефон СБП, чтобы он появился здесь."),
            LocalizedText("Nouvelle carte", "New card", "Новая карта"),
            LocalizedText("Nouveau téléphone SBP", "New SBP phone", "Новый телефон СБП"),
            LocalizedText("Choisir la banque", "Choose bank", "Выберите банк"),
            LocalizedText("Numéro de carte", "Card number", "Номер карты"),
            LocalizedText("Numéro de téléphone", "Phone number", "Номер телефона"),
            LocalizedText("Annuler", "Cancel", "Отмена"),
            LocalizedText("Enregistrer la carte", "Save card", "Сохранить карту"),
            LocalizedText("Enregistrer", "Save", "Сохранить"),
            LocalizedText("Modifier la destination", "Edit destination", "Изменить назначение"),
            LocalizedText("Entrez la nouvelle carte. L'ancienne sera remplacée après enregistrement.", "Enter the new card. The previous one will be replaced after saving.", "Введите новую карту. Старая будет заменена после сохранения."),
            LocalizedText("Entrez la nouvelle destination SBP. L'ancienne sera remplacée après enregistrement.", "Enter the new SBP destination. The previous one will be replaced after saving.", "Введите новое назначение СБП. Старое будет заменено после сохранения."),
            LocalizedText("Libellé affiché", "Display label", "Отображаемое название"),
            LocalizedText("Nouveau numéro de carte", "New card number", "Новый номер карты"),
            LocalizedText("Nouveau numéro de téléphone", "New phone number", "Новый номер телефона"),
            LocalizedText("Aucun moyen de réception", "No receiving method", "Нет способов получения"),
            LocalizedText("Ajoutez une carte ou un téléphone SBP pour commencer.", "Add a card or SBP phone to start.", "Добавьте карту или телефон СБП, чтобы начать."),
            LocalizedText("Modifier", "Edit", "Изменить"),
            LocalizedText("Définir", "Set", "Выбрать"),
            LocalizedText("Désactiver", "Disable", "Отключить"),
            LocalizedText("Supprimer", "Delete", "Удалить"),
            LocalizedText("Désactiver ce moyen ?", "Disable this method?", "Отключить этот способ?"),
            LocalizedText("Il ne sera plus proposé pour les nouveaux paiements.", "It will no longer be offered for new payments.", "Он больше не будет предлагаться для новых платежей."),
            LocalizedText("Supprimer ce moyen ?", "Delete this method?", "Удалить этот способ?"),
            LocalizedText("La destination masquée disparaîtra de cette liste.", "The masked destination will disappear from this list.", "Маскированное назначение исчезнет из списка."),
            LocalizedText("Actif", "Active", "Активно"),
            LocalizedText("À configurer", "To configure", "Настроить"),
            LocalizedText("Ventes", "Sales", "Продажи"),
            LocalizedText("Ventes confirmées", "Confirmed sales", "Подтвержденные продажи"),
            LocalizedText("Suivez les commandes reliées aux paiements confirmés.", "Track orders linked to confirmed payments.", "Отслеживайте заказы, связанные с подтвержденными платежами."),
            LocalizedText("VENTES CONFIRMÉES", "CONFIRMED SALES", "ПОДТВЕРЖДЕННЫЕ ПРОДАЖИ"),
            LocalizedText("MONTANT CONFIRMÉ", "CONFIRMED AMOUNT", "ПОДТВЕРЖДЕННАЯ СУММА"),
            LocalizedText("TAUX DE CONFIRMATION", "CONFIRMATION RATE", "ДОЛЯ ПОДТВЕРЖДЕНИЙ"),
            LocalizedText("Activité business", "Business activity", "Активность бизнеса"),
            LocalizedText("Paiements confirmés sur la période", "Confirmed payments over the period", "Подтвержденные платежи за период"),
            LocalizedText("Les courbes apparaîtront après vos premières ventes confirmées.", "Charts will appear after your first confirmed sales.", "Графики появятся после первых подтвержденных продаж."),
            LocalizedText("Confirmé", "Confirmed", "Подтверждено"),
            LocalizedText("Aucune vente confirmée", "No confirmed sale", "Подтвержденных продаж нет"),
            LocalizedText("Vos ventes apparaîtront ici après confirmation des paiements.", "Your sales will appear here after payment confirmation.", "Продажи появятся здесь после подтверждения платежей."),
            LocalizedText("Voir les paiements à confirmer", "View payments to confirm", "Смотреть платежи на проверку"),
            LocalizedText("Recherche des banques compatibles", "Compatible banks", "Совместимые банки"),
            LocalizedText("SwimPay vérifie uniquement les banques compatibles sur ce téléphone.", "SwimPay only checks compatible banks on this phone.", "SwimPay проверяет только совместимые банки на этом телефоне."),
            LocalizedText("SwimPay Intelligence activée", "SwimPay Intelligence enabled", "SwimPay Intelligence включена"),
            LocalizedText("Peut être activée", "Can be enabled", "Можно включить"),
            LocalizedText("Installez l'application bancaire", "Install the banking app", "Установите банковское приложение"),
            LocalizedText("Activer cette banque", "Enable this bank", "Включить этот банк"),
            LocalizedText("Téléphone Receiver", "Receiver phone", "Телефон Receiver"),
            LocalizedText("Ce téléphone permet à SwimPay de détecter les paiements reçus.", "This phone lets SwimPay detect received payments.", "Этот телефон помогает SwimPay обнаруживать полученные платежи."),
            LocalizedText("RÉACTIVER L'ACCÈS", "RE-ENABLE ACCESS", "ВКЛЮЧИТЬ ДОСТУП"),
            LocalizedText("Mode de confirmation", "Confirmation mode", "Режим подтверждения"),
            LocalizedText("Choisissez le niveau d'aide pour vérifier vos paiements.", "Choose the level of help for reviewing payments.", "Выберите уровень помощи для проверки платежей."),
            LocalizedText("Mode manuel V1", "Manual mode V1", "Ручной режим V1"),
            LocalizedText("Chaque paiement doit être confirmé par vous.", "Each payment must be confirmed by you.", "Каждый платеж подтверждаете вы."),
            LocalizedText("Confirmation manuelle", "Manual confirmation", "Ручное подтверждение"),
            LocalizedText("Assistance de revue", "Review assistance", "Помощь при проверке"),
            LocalizedText("SwimPay prépare les indices, vous décidez.", "SwimPay prepares the clues; you decide.", "SwimPay готовит подсказки, решение принимаете вы."),
            LocalizedText("Lecture seule", "Read only", "Только просмотр"),
            LocalizedText("Sécurité", "Security", "Безопасность"),
            LocalizedText("Apparence", "Appearance", "Оформление"),
            LocalizedText("Langue", "Language", "Язык"),
            LocalizedText("Centre d'aide", "Help center", "Центр помощи"),
            LocalizedText("Contacter le support", "Contact support", "Написать в поддержку"),
            LocalizedText("Rechercher", "Search", "Поиск"),
            LocalizedText("Sujet", "Subject", "Тема"),
            LocalizedText("Message", "Message", "Сообщение"),
            LocalizedText("Liez Google pour retrouver le compte, puis protégez l'accès à l'app.", "Link Google to recover the account, then protect app access.", "Свяжите Google для восстановления аккаунта и защитите доступ к приложению."),
            LocalizedText("Verrouillage de l'app", "App lock", "Блокировка приложения"),
            LocalizedText("La sécurité du téléphone protège uniquement l'interface. Le Receiver continue en arrière-plan.", "Phone security only protects the interface. The Receiver keeps running in the background.", "Защита телефона защищает только интерфейс. Receiver продолжает работать в фоне."),
            LocalizedText("Délai actif", "Active timeout", "Активная задержка"),
            LocalizedText("Utiliser ce délai", "Use this timeout", "Использовать эту задержку"),
            LocalizedText("Compte Google lié", "Google account linked", "Аккаунт Google привязан"),
            LocalizedText("Lier le compte Google", "Link Google account", "Привязать аккаунт Google"),
            LocalizedText("Sauvegarde ce profil marchand pour une future reconnexion avec Google.", "Saves this merchant profile for future Google sign-in.", "Сохраняет этот профиль продавца для будущего входа через Google."),
            LocalizedText("Lié", "Linked", "Привязан"),
            LocalizedText("Reconnexion", "Reconnect", "Повторный вход"),
            LocalizedText("Signaux de paiement", "Payment signals", "Платежные сигналы"),
            LocalizedText("SwimPay lit uniquement les notifications bancaires autorisées, les filtre, les rédacte et les envoie au backend.", "SwimPay only reads authorized bank notifications, filters them, redacts them and sends them to the backend.", "SwimPay читает только разрешенные банковские уведомления, фильтрует, редактирует и отправляет их на сервер."),
            LocalizedText("J'ai payé", "I paid", "Я оплатил"),
            LocalizedText("Cette action arme le suivi côté commande. Elle ne confirme jamais un paiement.", "This arms order-side tracking. It never confirms a payment.", "Это включает отслеживание заказа. Это никогда не подтверждает платеж."),
            LocalizedText("Le marchand décide. Le webhook final part seulement après confirmation manuelle.", "The merchant decides. The final webhook is sent only after manual confirmation.", "Решение принимает продавец. Финальный вебхук отправляется только после ручного подтверждения."),
            LocalizedText("Webhook", "Webhook", "Вебхук"),
            LocalizedText("Les webhooks publics V1 restent limités au résultat final confirmé, rejeté ou expiré.", "Public V1 webhooks stay limited to the final confirmed, rejected or expired result.", "Публичные вебхуки V1 ограничены финальным результатом: подтверждено, отклонено или истекло."),
            LocalizedText("Receiver hors ligne", "Receiver offline", "Receiver не в сети"),
            LocalizedText("Vérifiez l'accès aux notifications, les banques activées et la connexion du téléphone.", "Check notification access, enabled banks and phone connectivity.", "Проверьте доступ к уведомлениям, активные банки и соединение телефона."),
            LocalizedText("Aide courte, sûre et compatible avec la vérité produit V1.", "Short help aligned with the V1 product truth.", "Краткая помощь, соответствующая логике продукта V1."),
            LocalizedText("Aucun résultat", "No result", "Нет результатов"),
            LocalizedText("Essayez un autre mot-clé.", "Try another keyword.", "Попробуйте другое ключевое слово."),
            LocalizedText("Envoyez une demande sans texte sensible, secret, numéro complet, PIN, CVV ou code SMS.", "Send a request without sensitive text, secrets, full numbers, PIN, CVV or SMS codes.", "Отправьте запрос без чувствительного текста, секретов, полных номеров, PIN, CVV или SMS-кодов."),
            LocalizedText("Envoyer", "Send", "Отправить"),
            LocalizedText("Demande envoyée", "Request sent", "Запрос отправлен"),
            LocalizedText("SwimPay verrouille", "SwimPay is locked", "SwimPay заблокирован"),
            LocalizedText("Déverrouiller", "Unlock", "Разблокировать"),
            LocalizedText("Recevez vos paiements plus facilement", "Receive payments more easily", "Получайте платежи проще"),
            LocalizedText("SwimPay détecte les paiements reçus, vous aide à les confirmer et prévient votre site ou votre application.", "SwimPay detects received payments, helps you confirm them and updates your site or app.", "SwimPay обнаруживает полученные платежи, помогает подтвердить их и уведомляет ваш сайт или приложение."),
            LocalizedText("Détection rapide", "Fast detection", "Быстрое обнаружение"),
            LocalizedText("Repérez plus vite les paiements reçus.", "Spot received payments faster.", "Быстрее находите полученные платежи."),
            LocalizedText("Confirmation simple", "Simple confirmation", "Простое подтверждение"),
            LocalizedText("Confirmez ou rejetez en quelques secondes.", "Confirm or reject in seconds.", "Подтверждайте или отклоняйте за секунды."),
            LocalizedText("Business connecté", "Connected business", "Подключенный бизнес"),
            LocalizedText("Votre site ou application reçoit la mise à jour.", "Your site or app receives the update.", "Ваш сайт или приложение получает обновление."),
            LocalizedText("Commencer", "Start", "Начать"),
            LocalizedText("Accès notifications", "Notification access", "Доступ к уведомлениям"),
            LocalizedText("Connectez votre téléphone", "Connect your phone", "Подключите телефон"),
            LocalizedText("SwimPay a besoin d'accéder aux notifications de cet appareil pour fonctionner.", "SwimPay needs notification access on this device to work.", "SwimPay нужен доступ к уведомлениям на этом устройстве."),
            LocalizedText("Activé", "Enabled", "Включено"),
            LocalizedText("Accès nécessaire", "Access required", "Нужен доступ"),
            LocalizedText("L'accès notifications est activé.", "Notification access is enabled.", "Доступ к уведомлениям включен."),
            LocalizedText("Activez l'accès aux notifications pour détecter les paiements reçus.", "Enable notification access to detect received payments.", "Включите доступ к уведомлениям для обнаружения полученных платежей."),
            LocalizedText("SwimPay ne lit pas vos SMS et ne contrôle pas votre banque.", "SwimPay does not read SMS or control your bank.", "SwimPay не читает SMS и не управляет вашим банком."),
            LocalizedText("Continuer", "Continue", "Продолжить"),
            LocalizedText("Activer l'accès", "Enable access", "Включить доступ"),
            LocalizedText("Choisissez vos banques", "Choose your banks", "Выберите банки"),
            LocalizedText("SwimPay recherche uniquement les banques compatibles.", "SwimPay only looks for compatible banks.", "SwimPay ищет только совместимые банки."),
            LocalizedText("Activer ces banques", "Enable these banks", "Включить эти банки"),
            LocalizedText("Recherche en cours", "Searching", "Поиск"),
            LocalizedText("Les banques compatibles apparaissent ici sans parcourir toutes les applications.", "Compatible banks appear here without scanning every app.", "Совместимые банки появятся здесь без просмотра всех приложений."),
            LocalizedText("Recherche terminée", "Search complete", "Поиск завершен"),
            LocalizedText("Aucune banque détectée", "No bank detected", "Банки не обнаружены"),
            LocalizedText("{count} banque(s) activée(s).", "{count} bank(s) enabled.", "Включено банков: {count}."),
            LocalizedText("Sélectionnez les banques détectées que vous utilisez.", "Select the detected banks you use.", "Выберите обнаруженные банки, которыми вы пользуетесь."),
            LocalizedText("Vous pourrez configurer une banque compatible plus tard.", "You can configure a compatible bank later.", "Совместимый банк можно настроить позже."),
            LocalizedText("Recherche à relancer", "Search to retry", "Повторите поиск"),
            LocalizedText("Réessayez dans quelques instants.", "Try again in a moment.", "Попробуйте еще раз через несколько секунд."),
            LocalizedText("Les banques compatibles apparaîtront ici.", "Compatible banks will appear here.", "Совместимые банки появятся здесь."),
            LocalizedText("Vous pourrez continuer et configurer une banque plus tard.", "You can continue and configure a bank later.", "Можно продолжить и настроить банк позже."),
            LocalizedText("Activée", "Enabled", "Включена"),
            LocalizedText("Détectée", "Detected", "Обнаружена"),
            LocalizedText("Non détectée", "Not detected", "Не обнаружена"),
            LocalizedText("Vos clients utiliseront ces informations pour vous payer sur {bank}.", "Customers will use this information to pay you via {bank}.", "Клиенты будут использовать эти данные для оплаты через {bank}."),
            LocalizedText("Moyen de réception", "Receiving method", "Способ получения"),
            LocalizedText("Ajoutez votre moyen de réception", "Add your receiving method", "Добавьте способ получения"),
            LocalizedText("Ajoutez une carte ou un téléphone SBP marchand et associez-le à une banque compatible.", "Add a merchant card or SBP phone and link it to a compatible bank.", "Добавьте карту продавца или телефон СБП и свяжите его с совместимым банком."),
            LocalizedText("Carte bancaire", "Bank card", "Банковская карта"),
            LocalizedText("Recevez les paiements sur votre carte.", "Receive payments on your card.", "Получайте платежи на карту."),
            LocalizedText("Pratique pour les virements via SBP.", "Useful for SBP-style phone transfers.", "Удобно для переводов по СБП."),
            LocalizedText("Identifiant utilisé seulement pour l'enregistrement", "Identifier used only for saving", "Идентификатор используется только для сохранения"),
            LocalizedText("Enregistrer et continuer", "Save and continue", "Сохранить и продолжить"),
            LocalizedText("Site ou application", "Site or app", "Сайт или приложение"),
            LocalizedText("Intégration développeur", "Developer integration", "Интеграция разработчика"),
            LocalizedText("Integration active", "Integration active", "Интеграция активна"),
            LocalizedText("Integration a configurer", "Integration to configure", "Интеграцию нужно настроить"),
            LocalizedText("Site ou application à configurer", "Site or app to configure", "Сайт или приложение нужно настроить"),
            LocalizedText("Votre site ou application reçoit une notification quand un paiement change de statut.", "Your site or app receives a notification when a payment status changes.", "Ваш сайт или приложение получает уведомление, когда статус платежа меняется."),
            LocalizedText("SwimPay backend genere les identifiants. Le SDK les utilise cote app externe.", "The SwimPay backend generates identifiers. The SDK uses them in the external app.", "Backend SwimPay создает идентификаторы. SDK использует их во внешнем приложении."),
            LocalizedText("Vous pouvez continuer à utiliser SwimPay. Les mises à jour automatiques seront disponibles après connexion.", "You can keep using SwimPay. Automatic updates will be available after connection.", "Вы можете продолжать пользоваться SwimPay. Автоматические обновления будут доступны после подключения."),
            LocalizedText("URL de notification", "Notification URL", "URL уведомлений"),
            LocalizedText("Non configurée", "Not configured", "Не настроено"),
            LocalizedText("Action requise", "Action required", "Требуется действие"),
            LocalizedText("Optionnel", "Optional", "Необязательно"),
            LocalizedText("Statut", "Status", "Статус"),
            LocalizedText("Session mobile requise", "Mobile session required", "Нужна мобильная сессия"),
            LocalizedText("Cle publique", "Public key", "Публичный ключ"),
            LocalizedText("Cle API", "API key", "API-ключ"),
            LocalizedText("Evenements publics", "Public events", "Публичные события"),
            LocalizedText("Contrat marchand", "Merchant contract", "Контракт продавца"),
            LocalizedText("Enregistrer URL", "Save URL", "Сохранить URL"),
            LocalizedText("Tester", "Test", "Проверить"),
            LocalizedText("Créer clé API", "Create API key", "Создать API-ключ"),
            LocalizedText("Rotation clé", "Rotate key", "Ротация ключа"),
            LocalizedText("Rotation secret webhook", "Rotate webhook secret", "Ротация секрета webhook"),
            LocalizedText("Guide SDK (PDF)", "SDK guide (PDF)", "Руководство SDK (PDF)"),
            LocalizedText("Export staging", "Staging export", "Экспорт staging"),
            LocalizedText("À placer dans l'environnement de l'app externe. Android et le navigateur ne reçoivent pas de secret SDK.", "Place this in the external app environment. Android and the browser do not receive an SDK secret.", "Поместите это в окружение внешнего приложения. Android и браузер не получают секрет SDK."),
            LocalizedText("Connectez votre site ou application", "Connect your site or app", "Подключите сайт или приложение"),
            LocalizedText("Recevez une mise à jour après votre validation manuelle.", "Receive an update after your manual validation.", "Получайте обновление после ручной проверки."),
            LocalizedText("Configuration reportée", "Configuration postponed", "Настройка отложена"),
            LocalizedText("Prêt à ajouter", "Ready to add", "Готово к добавлению"),
            LocalizedText("Vous entrez dans l'app maintenant. Le webhook pourra être ajouté plus tard.", "You enter the app now. The webhook can be added later.", "Вы входите в приложение сейчас. Вебхук можно добавить позже."),
            LocalizedText("Ajoutez un endpoint pour lancer ensuite un test webhook backend.", "Add an endpoint, then run a backend webhook test.", "Добавьте endpoint, затем запустите серверный тест вебхука."),
            LocalizedText("Ajouter maintenant", "Add now", "Добавить сейчас"),
            LocalizedText("Configurer plus tard", "Configure later", "Настроить позже"),
            LocalizedText("Test", "Test", "Тест"),
            LocalizedText("Test webhook", "Webhook test", "Тест вебхука"),
            LocalizedText("Le test est déclenché par le backend vers votre endpoint. Android ne traite aucune notification réelle et ne confirme aucun paiement.", "The backend triggers the test toward your endpoint. Android processes no real notification and confirms no payment.", "Тест запускается сервером на ваш endpoint. Android не обрабатывает реальные уведомления и не подтверждает платежи."),
            LocalizedText("Lancer le test webhook", "Run webhook test", "Запустить тест вебхука"),
            LocalizedText("Webhook prêt", "Webhook ready", "Вебхук готов"),
            LocalizedText("Action nécessaire", "Action required", "Требуется действие"),
            LocalizedText("Le backend peut envoyer un événement de test vers votre endpoint configuré.", "The backend can send a test event to your configured endpoint.", "Сервер может отправить тестовое событие на настроенный endpoint."),
            LocalizedText("Réussi", "Done", "Готово"),
            LocalizedText("Réessayer", "Retry", "Повторить"),
            LocalizedText("Chargement", "Loading", "Загрузка"),
            LocalizedText("Connexion en attente", "Connection pending", "Ожидание подключения"),
            LocalizedText("Réception", "Receiving", "Приём"),
            LocalizedText("Appareil", "Device", "Устройство"),
            LocalizedText("Préférences", "Preferences", "Настройки"),
            LocalizedText("Abonnement", "Subscription", "Подписка"),
            LocalizedText("Marchand", "Merchant", "Продавец"),
            LocalizedText("Boutique", "Shop", "Магазин"),
            LocalizedText("Compte vérifié", "Verified account", "Аккаунт подтверждён"),
            LocalizedText("Profil marchand", "Merchant profile", "Профиль продавца"),
            LocalizedText("Entreprise & vérification (KYC)", "Business & verification (KYC)", "Бизнес и проверка (KYC)"),
            LocalizedText("Devises & taux", "Currencies & rates", "Валюты и курсы"),
            LocalizedText("Portefeuilles de réception", "Receiving wallets", "Кошельки для приёма"),
            LocalizedText("Confirmation automatique", "Automatic confirmation", "Автоподтверждение"),
            LocalizedText("Provenance & sécurité", "Provenance & security", "Происхождение и безопасность"),
            LocalizedText("Accès aux notifications", "Notification access", "Доступ к уведомлениям"),
            LocalizedText("Capture de signaux", "Signal capture", "Сбор сигналов"),
            LocalizedText("Appareils liés", "Linked devices", "Связанные устройства"),
            LocalizedText("Thème", "Theme", "Тема"),
            LocalizedText("Clair", "Light", "Светлая"),
            LocalizedText("Français", "French", "Французский"),
            LocalizedText("Forfait", "Plan", "Тариф"),
            LocalizedText("Premium", "Premium", "Premium"),
            LocalizedText("Facturation", "Billing", "Оплата"),
            LocalizedText("Confidentialité", "Privacy", "Конфиденциальность"),
            LocalizedText("Conditions", "Terms", "Условия")
        ).associateBy { it.fr }

        private val fr = PremiumLocalizedCopy(
            welcomeTitle = "Bienvenue sur SwimPay",
            welcomeBody = "Choisissez comment ouvrir votre espace marchand sur ce téléphone.",
            createAccount = "Créer un compte",
            signIn = "Se connecter",
            chooseProfileTitle = "Choisissez votre profil",
            sameRights = "Même accès dans l'app, quel que soit le profil choisi.",
            personalProfile = "Profil personnel",
            personalProfileBody = "Pour démarrer simplement avec un compte marchand léger.",
            commerceProfile = "Profil commerce",
            commerceProfileBody = "Pour nommer une activité ou une boutique sans changer les droits.",
            recoverTitle = "Retrouver un compte",
            recoverBody = "Choisissez un moyen de récupération pour une session déjà créée.",
            googleRecovery = "Continuer avec Google",
            googleRecoveryBody = "Récupérer un compte déjà lié pour la connexion.",
            terminalTitle = "Terminal Marchand",
            paymentsGroup = "PAIEMENTS",
            banks = "Banques",
            receivingMethods = "Moyens de réception",
            confirmationMode = "Mode de confirmation",
            businessGroup = "BUSINESS",
            developerIntegration = "Intégration développeur",
            sales = "Ventes",
            notifications = "Notifications",
            applicationGroup = "APPLICATION",
            appearance = "Apparence",
            language = "Langue",
            security = "Sécurité",
            helpGroup = "AIDE",
            support = "Contacter le support",
            helpCenter = "Centre d'aide",
            signOut = "SE DÉCONNECTER",
            languageBody = "Choisissez la langue de l'interface marchand.",
            appearanceBody = "Le changement est appliqué immédiatement à l'interface.",
            theme = "Thème",
            choose = "Choisir",
            active = "Actif"
        )

        private val en = PremiumLocalizedCopy(
            welcomeTitle = "Welcome to SwimPay",
            welcomeBody = "Choose how to open your merchant workspace on this phone.",
            createAccount = "Create account",
            signIn = "Sign in",
            chooseProfileTitle = "Choose your profile",
            sameRights = "Same app access, whichever profile you choose.",
            personalProfile = "Personal profile",
            personalProfileBody = "Start simply with a lightweight merchant account.",
            commerceProfile = "Business profile",
            commerceProfileBody = "Name a shop or activity without changing permissions.",
            recoverTitle = "Recover an account",
            recoverBody = "Choose a recovery method for an existing mobile session.",
            googleRecovery = "Continue with Google",
            googleRecoveryBody = "Recover an account already linked for sign-in.",
            terminalTitle = "Merchant Terminal",
            paymentsGroup = "PAYMENTS",
            banks = "Banks",
            receivingMethods = "Receiving methods",
            confirmationMode = "Confirmation mode",
            businessGroup = "BUSINESS",
            developerIntegration = "Developer integration",
            sales = "Sales",
            notifications = "Notifications",
            applicationGroup = "APPLICATION",
            appearance = "Appearance",
            language = "Language",
            security = "Security",
            helpGroup = "HELP",
            support = "Contact support",
            helpCenter = "Help center",
            signOut = "SIGN OUT",
            languageBody = "Choose the merchant interface language.",
            appearanceBody = "Theme changes apply immediately to the interface.",
            theme = "Theme",
            choose = "Choose",
            active = "Active"
        )

        private val ru = PremiumLocalizedCopy(
            welcomeTitle = "Добро пожаловать в SwimPay",
            welcomeBody = "Выберите, как открыть торговый кабинет на этом телефоне.",
            createAccount = "Создать аккаунт",
            signIn = "Войти",
            chooseProfileTitle = "Выберите профиль",
            sameRights = "Одинаковый доступ в приложении для любого профиля.",
            personalProfile = "Личный профиль",
            personalProfileBody = "Простой старт с легким торговым аккаунтом.",
            commerceProfile = "Профиль бизнеса",
            commerceProfileBody = "Назовите магазин или деятельность без изменения прав.",
            recoverTitle = "Восстановить аккаунт",
            recoverBody = "Выберите способ восстановления уже созданной сессии.",
            googleRecovery = "Продолжить с Google",
            googleRecoveryBody = "Восстановить аккаунт, уже привязанный для входа.",
            terminalTitle = "Торговый терминал",
            paymentsGroup = "ПЛАТЕЖИ",
            banks = "Банки",
            receivingMethods = "Способы получения",
            confirmationMode = "Режим подтверждения",
            businessGroup = "БИЗНЕС",
            developerIntegration = "Интеграция разработчика",
            sales = "Продажи",
            notifications = "Уведомления",
            applicationGroup = "ПРИЛОЖЕНИЕ",
            appearance = "Оформление",
            language = "Язык",
            security = "Безопасность",
            helpGroup = "ПОМОЩЬ",
            support = "Написать в поддержку",
            helpCenter = "Центр помощи",
            signOut = "ВЫЙТИ",
            languageBody = "Выберите язык интерфейса продавца.",
            appearanceBody = "Изменение темы применяется к интерфейсу сразу.",
            theme = "Тема",
            choose = "Выбрать",
            active = "Активно"
        )
    }
}

fun PremiumLanguageOption.mainTabLabel(tab: PremiumMainTab): String {
    return PremiumLocalizedCopy.forLanguage(this).mainTabLabel(tab)
}

fun PremiumLanguageOption.ui(text: String): String {
    return PremiumLocalizedCopy.forLanguage(this).ui(text)
}
