export const BankTemplateReasonCodes = {
  INCOMING_KEYWORD_DETECTED: 'incoming_keyword_detected',
  OUTGOING_KEYWORD_DETECTED: 'outgoing_keyword_detected',
  CASHBACK_KEYWORD_DETECTED: 'cashback_keyword_detected',
  REFUND_KEYWORD_DETECTED: 'refund_keyword_detected',
  FAILED_KEYWORD_DETECTED: 'failed_keyword_detected',
  PROMO_KEYWORD_DETECTED: 'promo_keyword_detected',
  BALANCE_KEYWORD_DETECTED: 'balance_keyword_detected',
  AMOUNT_EXTRACTED: 'amount_extracted',
  AMOUNT_MISSING: 'amount_missing',
  PHONE_EXTRACTED: 'phone_extracted',
  PHONE_MASKED: 'phone_masked',
  PHONE_MISSING: 'phone_missing',
  REFERENCE_EXTRACTED: 'reference_extracted',
  REFERENCE_TRUNCATED: 'reference_truncated',
  REFERENCE_MISSING: 'reference_missing',
  AMOUNT_ONLY_NEVER_AUTO_CONFIRM: 'amount_only_never_auto_confirm',
  BALANCE_DISAMBIGUATED: 'balance_disambiguated',
  NOT_CUSTOMER_TRANSFER: 'not_customer_transfer',
  TEMPLATE_MATCHED: 'template_matched',
  TEMPLATE_UNKNOWN: 'template_unknown',
  TEMPLATE_LOW_RELIABILITY: 'template_low_reliability',
  AMBIGUOUS_DIRECTION: 'ambiguous_direction',
  AUTO_CONFIRM_CANDIDATE: 'auto_confirm_candidate',
  REVIEW_REQUIRED: 'review_required',
} as const;
