server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /downloads/ {
    types {
      application/vnd.android.package-archive apk;
    }
    add_header Content-Disposition "attachment";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
